version: '3.8'

services:
  web:
    container_name: educore-dev-web
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-educore/educore_lms}:${DOCKER_TAG:-main}
    ports:
      - "8004:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - DATABASE_URL=postgresql://${DB_USER:-educore_user}:${DB_PASSWORD:-educore_pass}@db:5432/${DB_NAME:-educore_db}
      - ALLOWED_HOSTS=dev.educore-lms.com,localhost,127.0.0.1
      - ENVIRONMENT=development
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - educore_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    container_name: educore-dev-db
    image: postgres:15-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-educore_db}
      - POSTGRES_USER=${DB_USER:-educore_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-educore_pass}
    ports:
      - "5440:5432"
    restart: unless-stopped
    networks:
      - educore_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-educore_user} -d ${DB_NAME:-educore_db}"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    container_name: educore-dev-nginx
    image: nginx:alpine
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/var/www/html/static:ro
      - media_volume:/var/www/html/media:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - educore_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data_dev:
  static_volume:
  media_volume:

networks:
  educore_network:
    driver: bridge